### ISSUE TITLE
Refactor/namespace unit test classes

### ISSUE THREAD

**Issue by deni-zen** [deni-zen/csvelte#11]
My unit tests, as of now, are disorganized, inconsistent, and they only test the bare minimum. I need to refactor the tests to be consistent and easy to read. Somebody new to the code should be able to tell what's being tested and how just by looking at the tests. 
- [x] Convert all tests over to new CSVelteTest\UnitTestCase format
- [x] Use vfsStream where possible to test IO functionality 
- [x] Use stream wrappers to test http, ftp, etc. (if possible)
- [ ] Remove old csvelte/tests/files/*.csv files (see #3 - delete from entire history if possible)
- [x] Update build scripts, they will no longer need to download the zip/tarball of test CSV files
- [ ] Not really that big of a deal, but if you get time and you feel like it, delete tarball off AWS
- [x] Make sure coveralls build shows at least 95% coverage 
- [ ] Make sure scrutinizer is at least a 9.0

**Comment by deni-zen** [comment]
Oh and also, they aren't (consistently) namespaced.

**Comment by deni-zen** [comment]
For some reason, namespacing tests/CSVelte/TasterTest.php causes all its tests to fail. Removing the namespace makes it work fine. Its tests still get ran so it's not that...

**Comment by nozavroni** [comment]
Pushed to "Next Release" because although the code I wrote and actions I took went a very long way towards accomplishing all I set out to with this issue, it is really an ongoing problem and also there are still parts of the old-style tests that I have yet to port over and so rather than close this guy, I'll just push it along again...
